spring:
  application:
    name: sample-v1
  profiles:
    active:
      - local

  web:
    locale: zh_CN
  webflux:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  session:
    timeout: 7D
    store-type: none
    mongodb:
      collection-name: sessions
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${lijiajia3515.auth.server}/oauth2/jwks
  data:
    mongodb:
      auto-index-creation: true
      field-naming-strategy: com.lijiajia3515.cairo.mongo.data.mapping.model.UpperCamelCaseFieldNamingStrategy
      database: ${lijiajia3515.mongodb.database:hfhk-system}
      gridfs:
        bucket: ${lijiajia3515.mongodb.grfs.database:system}
        database: hfhk-store
      host: ${lijiajia3515.mongodb.host:localhost}
      port: ${lijiajia3515.mongodb.port:27017}
      username: ${lijiajia3515.mongodb.username:hfhk}
      password: ${lijiajia3515.mongodb.password:Hfhk.1320.}
      authentication-database: ${lijiajia3515.mongodb.authentication-database:hfhk}
  redis:
    database: ${lijiajia3515.redis.database:11}
    host: ${lijiajia3515.redis.host:localhost}
    port: ${lijiajia3515.redis.port:6379}
    password: ${lijiajia3515.redis.password:Hfhk-!@#-1230.}
    timeout: 10s
    lettuce:
      shutdown-timeout: 5000ms
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      server-addr: ${lijiajia3515.nacos.server-addr:localhost:8848}
      discovery:
        server-addr: ${lijiajia3515.nacos.discovery.server-addr:${hfhk.nacos.server-addr:localhost:8848}}
        namespace: ${lijiajia3515.nacos.discovery.namespace:${hfhk.nacos.namespace:hfhk}}
        group: ${lijiajia3515.nacos.discovery.group:${hfhk.nacos.group:hfhk}}
        metadata:
          version: v1

logging:
  level:
    root: info
    com.hfhk: debug
  file:
    name: /lijiajia3515/system/service/logs/hfhk.log

server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true

security:
  oauth2:
    client:
      id: ${random.value}
      client-id: ${hfhk.auth.client.id:hfhk_auth}
      client-secret: ${hfhk.auth.client.id:hfhk_auth}
      grant-type: client_credentials
      access-token-uri: http://${hfhk.auth.server:auth-server}/oauth2/token

feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 60000
  compression:
    request:
      min-request-size: 204000
  client:
    default-to-properties: true
    config:
      default:
        logger-level: FULL
management:
  endpoints:
    web:
      exposure:
        include: "*"

